apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: certificates.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: challenges.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: challenges.acme.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: clusterissuers.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: issuers.cert-manager.io
  - group: apiextensions.k8s.io
    jsonPointers:
    - /status
    kind: CustomResourceDefinition
    name: orders.acme.cert-manager.io
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.7.2
    helm:
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
