nodeExporter:
  enabled: false
grafana:
  adminPassword: acjvs2aU
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
  additionalDataSources:
  - name: VictoriaMetrics
    editable: false
    isDefault: true
    type: prometheus
    url: "https://vmselect.keenan.dev/select/0/prometheus/"
    version: 1
  persistence:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - "grafana.kcloud.keenan.dev"
    tls:
      - secretName: traefik-keenan-dev-tls
        hosts:
          - "grafana.kcloud.keenan.dev"
kubeProxy:
  enabled: true
  service:
    enabled: true
prometheus:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - "prometheus.kcloud.keenan.dev"
    tls:
      - secretName: traefik-keenan-dev-tls
        hosts:
          - "prometheus.kcloud.keenan.dev"
  prometheusSpec:
    remoteWrite:
    - url: "https://vminsert.keenan.dev/insert/0/prometheus/"
    storageSpec:
      emptyDir:
        medium: Memory
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: "false"
    additionalScrapeConfigs:
      - job_name: 'itb-scrape'
        static_configs:
          - targets: ['10.0.10.7:8000']
defaultRules:
  create: false
  rules:
    alertmanager: false
    etcd: false
    configReloaders: false
    general: false
    k8s: false
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverSlos: false
    kubelet: false
    kubeProxy: true
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    kubeStateMetrics: false
    network: false
    node: false
    nodeExporterAlerting: false
    nodeExporterRecording: false
    prometheus: false
    prometheusOperator: false
